"""
DreamPhase 3: Simulation - solving tomorrow's problems tonight.

The brain reviews today's unresolved problems, spins up isolated sandboxes
containing full microservice scaffolds (FastAPI app + tests), and verifies
them overnight. When the user wakes up, a deployable solution is already
waiting in their working memory.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List

from nexus.domain.entities.memory import Memory, MemoryType
from nexus.domain.ports.execution import ToolExecutor
from nexus.domain.ports.llm_provider import LLMProvider
from nexus.domain.ports.memory_repository import MemoryRepository, ShortTermMemory
from nexus.domain.ports.sandbox import Sandbox
from nexus.domain.value_objects.schema import JSONSchema


@dataclass
class SimulatedSolution:
    problem: str
    hypothesis: str
    verified: bool
    notes: str = ""
    scaffold: Dict[str, str] = field(default_factory=dict)  # deployable microservice files


@dataclass
class SimulationResult:
    problems_identified: int
    solutions_tested: int = 0
    solutions_verified: List[SimulatedSolution] = field(default_factory=list)
    deployments_ready: int = 0


_PROBLEM_SCHEMA = JSONSchema(
    type="object",
    properties={
        "problems": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "problem": {"type": "string"},
                    "context": {"type": "string"},
                },
                "required": ["problem"],
            },
        }
    },
    required=["problems"],
)

_MAIN_TEMPLATE = '''"""Scaffold for: {problem} - generated by NEXUS dream simulation."""
from fastapi import FastAPI
from pydantic import BaseModel

from logic import solve

app = FastAPI(title="nexus-sim-{slug}")

class InModel(BaseModel):
    data: dict = {{}}

class OutModel(BaseModel):
    ok: bool
    result: dict

@app.post("/execute")
async def execute(inp: InModel) -> OutModel:
    return OutModel(ok=True, result=solve(inp.data))

@app.get("/health")
async def health():
    return {{"status": "ok"}}
'''

_TEST_TEMPLATE = '''"""Tests for the scaffold generated for: {problem}"""
from fastapi.testclient import TestClient

from main import app

client = TestClient(app)


def test_health():
    resp = client.get("/health")
    assert resp.status_code == 200
    assert resp.json() == {{"status": "ok"}}


def test_execute():
    resp = client.post("/execute", json={{"""data""": {sample_input}}})
    assert resp.status_code == 200
    body = resp.json()
    assert body["ok"] is True
    assert body["result"] is not None
'''


class SimulationUseCase:
    """Overnight future-simulation engine - builds and verifies microservices."""

    def __init__(
        self,
        llm: LLMProvider,
        sandbox: Sandbox,
        executor: ToolExecutor,
        memory_repo: MemoryRepository,
        working_memory: ShortTermMemory,
    ) -> None:
        self._llm = llm
        self._sandbox = sandbox
        self._executor = executor
        self._memory_repo = memory_repo
        self._working_memory = working_memory

    async def run(self, unresolved_memories: List[Memory], max_sandboxes: int = 5) -> SimulationResult:
        result = SimulationResult(problems_identified=len(unresolved_memories))

        problems = await self._extract_problems(unresolved_memories)
        for problem in problems[:max_sandboxes]:
            solution = await self._simulate_solution(problem)
            result.solutions_tested += 1
            if solution.verified:
                result.solutions_verified.append(solution)
                result.deployments_ready += 1
                # Persist the verified solution as procedural memory
                await self._memory_repo.store(
                    Memory(
                        content=f"PROBLEM: {solution.problem}\nSOLUTION: {solution.hypothesis}",
                        memory_type=MemoryType.PROCEDURAL,
                        metadata={"origin": "dream_simulation"},
                    )
                )

        # Deliver findings (with deployable scaffolds) to working memory so the
        # cortex "already knows" at dawn.
        if result.solutions_verified:
            await self._working_memory.set(
                "dream:findings",
                {
                    "solutions": [
                        {"problem": s.problem, "solution": s.hypothesis, "notes": s.notes}
                        for s in result.solutions_verified
                    ],
                    "deployables": {
                        s.problem: s.scaffold for s in result.solutions_verified if s.scaffold
                    },
                    "generated_at": __import__("datetime").datetime.utcnow().isoformat(),
                },
                ttl_seconds=86400,
            )

        return result

    async def _extract_problems(self, memories: List[Memory]) -> List[str]:
        if not memories:
            return []
        try:
            structured = await self._llm.extract_structured(
                "\n---\n".join(m.content for m in memories),
                schema=_PROBLEM_SCHEMA,
                instructions=(
                    "Identify concrete, unresolved problems the user is facing. "
                    "Focus on actionable technical/work problems that could be solved with code."
                ),
            )
            return [p["problem"] for p in structured.get("problems", [])]
        except Exception:
            return []

    async def _simulate_solution(self, problem: str) -> SimulatedSolution:
        """Generate a candidate microservice scaffold and verify it in the sandbox."""
        solve_code = await self._write_solve_function(problem)
        if not solve_code:
            return SimulatedSolution(problem=problem, hypothesis="", verified=False, notes="LLM returned no code")

        scaffold = self._build_scaffold(problem, solve_code)
        try:
            sandbox_result = await self._sandbox.run_project(
                scaffold, test_command="python -m pytest -q", timeout=60
            )
        except Exception as exc:
            return SimulatedSolution(
                problem=problem, hypothesis=solve_code, verified=False, notes=str(exc), scaffold=scaffold
            )

        error = sandbox_result.get("error")
        verified = not error
        notes = error or sandbox_result.get("output", "").strip()[-200:] or "All tests passed"
        return SimulatedSolution(
            problem=problem,
            hypothesis=solve_code,
            verified=verified,
            notes=notes,
            scaffold=scaffold if verified else {},
        )

    async def _write_solve_function(self, problem: str) -> str:
        """Ask the LLM to author the core solve() function for the scaffold."""
        try:
            code = await self._llm.complete(
                [
                    {
                        "role": "system",
                        "content": (
                            "Write a single self-contained Python function `solve(input_data: dict) -> dict` "
                            "that solves this problem. Return ONLY code, no explanations.",
                        ),
                    },
                    {"role": "user", "content": problem},
                ]
            )
        except Exception:
            return ""

        if "```" in code:
            code = code.split("```")[1]
            if code.startswith("python"):
                code = code[len("python"):]
        return code.strip()

    def _build_scaffold(self, problem: str, solve_code: str) -> Dict[str, str]:
        """Assemble a deployable FastAPI microservice around the solve() function."""
        slug = "".join(ch for ch in problem.lower().replace(" ", "-") if ch.isalnum() or ch == "-")[:40] or "solve"
        sample_input = {"query": problem[:120]}
        return {
            "requirements.txt": "fastapi\nuvicorn\npydantic\nhttpx\npytest",
            "logic.py": solve_code,
            "main.py": _MAIN_TEMPLATE.format(problem=problem, slug=slug),
            "tests/test_main.py": _TEST_TEMPLATE.format(problem=problem, sample_input=repr(sample_input)),
        }
