"""
Local DeploymentProvider adapter - spins up tools as local FastAPI processes.

This gives NEXUS infrastructure control over its own tool ecosystem without
needing cloud credentials. Swap for Railway/Vercel providers for cloud runs.
"""

from __future__ import annotations

import asyncio
import socket
import tempfile
import uuid
from pathlib import Path
from typing import Dict

from nexus.domain.ports.deployment import DeploymentInfo, DeploymentProvider, DeploymentRequest

_TEMPLATE = '''"""
{tool_name} - self-generated by NEXUS
"""
import json
from fastapi import FastAPI
from pydantic import BaseModel
import {logic_module}

app = FastAPI(title="{tool_name}")

class InModel(BaseModel):
    data: dict = {{}}

@app.post("/execute")
async def execute(inp: InModel):
    result = {logic_module}.solve(inp.data)
    return {{"ok": True, "result": result}}
'''


class LocalDeployer(DeploymentProvider):
    """Deploys tool code to ephemeral local FastAPI servers."""

    def __init__(self, base_port: int = 9100) -> None:
        self._base_port = base_port
        self._deployments: Dict[str, DeploymentInfo] = {}
        self._processes: Dict[str, asyncio.subprocess.Process] = {}
        self._workdirs: Dict[str, str] = {}

    async def deploy(self, request: DeploymentRequest) -> DeploymentInfo:
        workdir = tempfile.mkdtemp(prefix="nexus-tool-")
        logic_file = Path(workdir) / "logic.py"
        logic_file.write_text(request.code)
        app_file = Path(workdir) / "main.py"
        app_file.write_text(
            _TEMPLATE.format(tool_name=request.name, logic_module="logic")
        )

        port = self._next_free_port()
        proc = await asyncio.create_subprocess_exec(
            "uvicorn", "main:app", "--host", "127.0.0.1", "--port", str(port),
            cwd=workdir,
            stdout=asyncio.subprocess.DEVNULL,
            stderr=asyncio.subprocess.DEVNULL,
        )
        await asyncio.sleep(1.5)  # give it a moment to boot

        deployment_id = str(uuid.uuid4())
        info = DeploymentInfo(
            endpoint=f"http://127.0.0.1:{port}",
            platform="local",
            deployment_id=deployment_id,
        )
        self._deployments[deployment_id] = info
        self._processes[deployment_id] = proc
        self._workdirs[deployment_id] = workdir
        return info

    async def scale(self, deployment_id: str, instances: int) -> None:
        # Local single-process; scale is a no-op. Cloud adapters implement real scaling.
        return None

    async def undeploy(self, deployment_id: str) -> None:
        proc = self._processes.pop(deployment_id, None)
        if proc:
            proc.terminate()
            try:
                await asyncio.wait_for(proc.wait(), timeout=5)
            except asyncio.TimeoutError:
                proc.kill()
        self._deployments.pop(deployment_id, None)

    def _next_free_port(self) -> int:
        sock = socket.socket()
        sock.bind(("127.0.0.1", 0))
        port = sock.getsockname()[1]
        sock.close()
        return port
